# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: PyProc Build and Release

on:
  push:
    tags:
      - v*

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Display Python Version
      run: python -c "import sys; print(sys.version)"

    - name: Clean build directory
      run: rm -rf ./dists ./pyproc.egg-info ./tests/*.csv ./tests/*.idx ./*csv ./*idx

    - name: Build Package
      run: |
        python -m pip install build
        python -m build

    - name: Upload distributions
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi

      steps:
        - name: Retrieve release distributions
          uses: actions/download-artifact@v4
          with:
            name: release-dists
            path: dist/

        - name: Publish rleease distributions to PyPI
          uses: pypa/gh-action-pypi-publish@release/v1
          with:
            package-dir: dist/
  
  
